"""Add ipv4 column to tbl_aws_instance

Revision ID: b21c5efa2141
Revises: b1592f66e069
Create Date: 2025-11-21 09:41:08.710137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21c5efa2141'
down_revision: Union[str, None] = 'b1592f66e069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_aws_instance', sa.Column('ipv4', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_aws_instance', 'ipv4')
    # ### end Alembic commands ###
